
services:
  server:
    build: ./server
    container_name: dform-server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  client:
    build: ./client
    container_name: dform-client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
